module.exports = {
    USER_COLLECTION: "users",
    TASK_COLLECTION: "tasks",
    SALT_ROUNDS: 10,
    HTTP_STATUS_CODE_BAD_REQUEST: 400,
    HTTP_STATUS_CODE_OK: 200,
    HTTP_STATUS_CODE_INTERNAL_ERROR: 500,
    HTTP_STATUS_CODE_NOT_FOUND: 404,
    JWT_SECRET_KEY: "0182018212910",
}


